-- app/supabase/migrations/0001_init_schema.sql
-- 本專案題庫內容走靜態 JSON（assets/json/），不建 course/chapters/questions/
-- sections 這類內容表。這裡只建授權與個人作答紀錄用的表，逐字對照
-- lib/core/services/lk_auth_service.dart、cloud_sync_service.dart、
-- study_logger.dart 實際查詢用到的表名與欄位名，不是重新設計。
-- students / license_keys 的後台欄位另外對照 web/admin.html（Task 12）。

create extension if not exists "uuid-ossp";

create table license_keys (
  id uuid primary key default uuid_generate_v4(),
  key_code text unique not null,
  batch_name text,
  max_uses int not null default 1,      -- 0 = 無限
  used_count int not null default 0,
  expires_at timestamptz not null,
  is_active boolean not null default true,
  notes text                            -- web/admin.html saveKey() payload 的「備註」
);

create table key_sessions (
  id uuid primary key default uuid_generate_v4(),
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  login_count int not null default 1,
  last_used_at timestamptz,
  unique (key_id, device_id)
);

-- lk_auth_service.dart 用 _sb.rpc('increment_key_used_count', params: {'k_id': keyId}) 呼叫
create or replace function increment_key_used_count(k_id uuid)
returns void as $$
  update license_keys set used_count = used_count + 1 where id = k_id;
$$ language sql;

create table key_favorites (
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  question_id text not null,
  created_at timestamptz not null default now(),
  unique (key_id, device_id, question_id)   -- cloud_sync_service.dart upsert onConflict: 'key_id,device_id,question_id'
);

create table key_wrong_answers (
  -- cloud_sync_service.dart 會 select('id, wrong_count')，沒有 id 欄位會 400
  id bigint generated by default as identity,
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  question_id text not null,
  wrong_count int not null default 1,
  last_wrong_at timestamptz not null default now(),
  unique (key_id, device_id, question_id)
);

create table students (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  unit_name text,
  employee_id text,
  key_id uuid references license_keys(id),
  key_code text,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  -- 以下四欄為 web/admin.html「學員管理」分頁的 students payload / 統計使用
  region text,
  email text,
  batch_name text,
  notes text,
  email_sent_at timestamptz
);

-- auto-register-student Edge Function 用 name+unit_name+employee_id 查同一人；
-- 刻意非 unique（同人重複註冊由 function 程式碼處理，非資料庫約束）
create index students_name_unit_emp_idx on students (name, unit_name, employee_id);

-- study_logger.dart 的 _insert() 直接把這些欄位當頂層物件送出
create table study_logs (
  id uuid primary key default uuid_generate_v4(),
  license_key text not null,
  event_type text not null,
  chapter_id text,
  section_id text,
  duration_seconds int,
  questions_total int,
  questions_correct int,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- 這些都是授權／個人作答紀錄表，沿用 insurance-exam-app／currency-insurance-exam
-- 現狀的信任模型：不加 RLS ownership 限制。原因：前端一律用 anon key +
-- 純 .eq('key_id', ...) 過濾，沒有 Supabase Auth session／JWT claim 可供
-- RLS 驗證「這個 key_id 真的屬於呼叫端」，加了只會讓現有程式碼打不通。
-- 這是跟三個既有站台一致的既有風險，不在本案中另外解決。
--
-- 新版 Supabase 專案可能對新建表預設自動開 RLS（currency 0003 踩過），
-- 在沒有任何 policy 下會讓 anon 全部被擋，所以明確關閉（不是新增 policy）。
alter table license_keys disable row level security;
alter table key_sessions disable row level security;
alter table key_favorites disable row level security;
alter table key_wrong_answers disable row level security;
alter table students disable row level security;
alter table study_logs disable row level security;
