-- app/supabase/migrations/0001_init_schema.sql
-- 本專案題庫內容走靜態 JSON（assets/json/），不建 course/chapters/questions/
-- sections 這類內容表。這裡只建授權與個人作答紀錄用的表，逐字對照
-- lib/core/services/lk_auth_service.dart、cloud_sync_service.dart、
-- study_logger.dart 實際查詢用到的表名與欄位名，不是重新設計。
-- students / license_keys 的後台欄位另外對照 web/admin.html（Task 12）。

create extension if not exists "uuid-ossp";

create table license_keys (
  id uuid primary key default uuid_generate_v4(),
  key_code text unique not null,
  batch_name text,
  max_uses int not null default 1,      -- 0 = 無限
  used_count int not null default 0,
  expires_at timestamptz not null,
  is_active boolean not null default true,
  notes text                            -- web/admin.html saveKey() payload 的「備註」
);

create table key_sessions (
  id uuid primary key default uuid_generate_v4(),
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  login_count int not null default 1,
  last_used_at timestamptz,
  unique (key_id, device_id)
);

-- lk_auth_service.dart 用 _sb.rpc('increment_key_used_count', params: {'k_id': keyId}) 呼叫
-- security definer：license_keys 開 RLS 後 anon 只能 select，沒有 definer 這個 RPC 會被擋（currency 0008）
create or replace function public.increment_key_used_count(k_id uuid)
returns void language sql security definer set search_path = public as $$
  update public.license_keys set used_count = used_count + 1 where id = k_id;
$$;

create table key_favorites (
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  question_id text not null,
  created_at timestamptz not null default now(),
  unique (key_id, device_id, question_id)   -- cloud_sync_service.dart upsert onConflict: 'key_id,device_id,question_id'
);

create table key_wrong_answers (
  -- cloud_sync_service.dart 會 select('id, wrong_count')，沒有 id 欄位會 400
  id bigint generated by default as identity,
  key_id uuid not null references license_keys(id) on delete cascade,
  device_id text not null,
  question_id text not null,
  wrong_count int not null default 1,
  last_wrong_at timestamptz not null default now(),
  unique (key_id, device_id, question_id)
);

create table students (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  unit_name text,
  employee_id text,
  key_id uuid references license_keys(id),
  key_code text,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  -- 以下四欄為 web/admin.html「學員管理」分頁的 students payload / 統計使用
  region text,
  email text,
  batch_name text,
  notes text,
  email_sent_at timestamptz
);

-- auto-register-student Edge Function 用 name+unit_name+employee_id 查同一人；
-- 刻意非 unique（同人重複註冊由 function 程式碼處理，非資料庫約束）
create index students_name_unit_emp_idx on students (name, unit_name, employee_id);

-- study_logger.dart 的 _insert() 直接把這些欄位當頂層物件送出
create table study_logs (
  id uuid primary key default uuid_generate_v4(),
  license_key text not null,
  event_type text not null,
  chapter_id text,
  section_id text,
  duration_seconds int,
  questions_total int,
  questions_correct int,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- RLS 模型：鏡像 currency-insurance-exam 目前的終態（其 migrations 0008 + 0009），
-- 不是較早的 0002/0003「全關 RLS」狀態（那會讓持有公開 anon key 的人能改/刪/清空
-- 所有授權碼與學員，且觸發 Supabase Security Advisor「RLS Disabled in Public」）。
--   * 學員端（anon key）對 license_keys 只做 SELECT，對 students 完全不碰。
--   * auto-register-student Edge Function 用 service_role，會繞過 RLS。
--   * 後台 web/admin.html 以 Supabase Auth 登入 admin@skl.com.tw，才能讀寫 students/license_keys。
--     Task 5 必須在 Supabase Dashboard 建立 Email 剛好是 admin@skl.com.tw 的 Auth 使用者。
--   * key_sessions/key_favorites/key_wrong_answers/study_logs 學員端沒有 Auth session 可供
--     ownership 驗證，沿用既有信任模型：開 RLS + 全開 policy（client_all），純粹消除 Advisor ERROR。
alter table students enable row level security;
create policy students_admin_all on students
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'admin@skl.com.tw')
  with check ((auth.jwt() ->> 'email') = 'admin@skl.com.tw');

alter table license_keys enable row level security;
create policy license_keys_read on license_keys
  for select to anon, authenticated using (true);
create policy license_keys_admin_write on license_keys
  for all to authenticated
  using ((auth.jwt() ->> 'email') = 'admin@skl.com.tw')
  with check ((auth.jwt() ->> 'email') = 'admin@skl.com.tw');

do $$
declare t text;
begin
  foreach t in array array['key_sessions','key_favorites','key_wrong_answers','study_logs'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists client_all on public.%I', t);
    execute format('create policy client_all on public.%I for all to anon, authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- TRUNCATE 不受 RLS 限制，PostgREST 也用不到，收回
revoke truncate on all tables in schema public from anon, authenticated;
